id: P422D93A4
initial_creation_type: input
source_metadata:
  title: Khenchen Ngawang Palzang Series
  language: bo
  description: 'Texts by the great Dzogchen master Khenchen Ngawang Palzang (ngag
    dbang dpal bzang, 1879–1941), also known as Khenpo Ngakchung:'
  volume:
    432b789978f143fe84f3148fa3687109:
      title: Seeds of the Four Philosophical Schools
      parent: Buddhist Philosophy
    251172bb11454be6953280cbdf60fb32:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Dzogchen
    d633fb40d7524906b0dbd905517706d3:
      title: The Five Wisdoms
      parent: Dzogchen
    cc456f06e2b7457093c94b89ea2a866c:
      title: Prayer to Pema Tötreng Tsal
      parent: Guru Rinpoche Prayers
    dcbf0140841a4decbe80dd7a444f1856:
      title: Brief Succession of Lives Prayer
      parent: Prayers
    4ee0e76b6e104c539c64f279be1d6072:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    ad07d66c557e44659d794ce20c1d8031:
      title: Prayer for this Life, the Next and the Bardos
      parent: Prayers
    27db8cdefd7a442ba876b9fa0f00a3c2:
      title: Prayer to Khenpo Ngawang Palzang
      parent: Prayers
    c0f2ef56ea744a3c853b946d7063590e:
      title: Brief Homage to the Twenty-One Tārās
      parent: Tārā
created_at: '2022-03-01T00:22:24.761660'
last_modified_at: '2022-03-01T00:22:24.761664'
statistics:
  total_words: 3076
  total_non_words: 237
quality:
  non_words_ratio: 0.08
